#pragma once
// Auto-generated by offsets.win

#include <cstdint>

namespace Decryptions
{
	namespace BaseNetworkable_Decryption
	{
		// decryptions::base_networkable_one
		std::uintptr_t base_networkable_one(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x93748B89u;
		        eax = eax + 0x96CB9157u;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::base_networkable_two
		std::uintptr_t base_networkable_two(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x6FF3D846u;
		        eax = (eax << 0x15) | (eax >> 0x0B);
		        eax = eax + 0x7B132AD0u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace ActiveItem_Decryption
	{
		// decryptions::decrypt_active_item
		std::uintptr_t decrypt_active_item(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax - 0x44519A01u;
		        eax = eax ^ 0xEF6D88Cu;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        eax = eax - 0x48BD351Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_0xE0
		std::uintptr_t decrypt_0xE0(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xCE60325Bu;
		        eax = (eax << 0x13) | (eax >> 0x0D);
		        eax = eax + 0xA48959Fu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_PlayerInventory
		std::uintptr_t decrypt_PlayerInventory(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x2B99655Bu;
		        eax = eax + 0xC749C554u;
		        eax = (eax << 0x07) | (eax >> 0x19);
		        eax = eax + 0x784A90B1u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_PlayerInventory_2
		std::uintptr_t decrypt_PlayerInventory_2(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax - 0x4DC14BB8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_PlayerEyes
		std::uintptr_t decrypt_PlayerEyes(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x15) | (eax << 0x0B);
		        eax = eax - 0x3BAD30FEu;
		        eax = eax ^ 0x7790C0A0u;
		        eax = eax + 0x6CE48E8Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_ulong
		std::uintptr_t decrypt_ulong(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xC8390462u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        eax = eax - 0x4DC14BB8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_clothingAccuracyBonus
		std::uintptr_t decrypt_clothingAccuracyBonus(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x3;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0C) | (eax << 0x14);
		        eax = eax + 0x9AC59D54u;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        eax = eax ^ 0xC92CB593u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt
		std::uintptr_t decrypt(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax << 0x19) | (eax >> 0x07);
		        eax = eax + 0x5BFDBA25u;
		        eax = (eax << 0x06) | (eax >> 0x1A);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_2
		std::uintptr_t decrypt_2(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax - 0x5u;
		        eax = eax + esi;
		        eax = eax + 0xFFFF2400u;
		        eax = eax + 0xFFFFFFFBu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_3
		std::uintptr_t decrypt_3(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x1A) | (eax << 0x06);
		        eax = eax ^ 0x1D918A33u;
		        eax = eax + 0xD7232282u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace PlayerInventory_Decryption
	{
		// decryptions::decrypt_PlayerInventory
		std::uintptr_t decrypt_PlayerInventory(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x2B99655Bu;
		        eax = eax + 0xC749C554u;
		        eax = (eax << 0x07) | (eax >> 0x19);
		        eax = eax + 0x784A90B1u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace Convar_Graphics_Decryption
	{
		// decryptions::decrypt_int
		uint64_t encrypt_decrypt_int(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax ^ 0xE40D1FBAu;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_int(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax ^ 0xE40D1FBAu;
		    return eax;
		}

		// decryptions::decrypt_float
		std::uintptr_t decrypt_float(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x93748B89u;
		        eax = eax + 0x96CB9157u;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_bool
		uint64_t encrypt_decrypt_bool(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax - 0x2u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_bool(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax + 0x2u;
		    return eax;
		}

		// decryptions::decrypt_int
		std::uintptr_t decrypt_int(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x08) | (eax << 0x18);
		        eax = eax + 0x7C64D3E6u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_int
		std::uintptr_t decrypt_int(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax - 0x44519A01u;
		        eax = eax ^ 0xEF6D88Cu;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        eax = eax - 0x48BD351Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::fov
		uint64_t encrypt_fov(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax ^ 0xCC78692Eu;
		    eax = (eax << 0x05) | (eax >> 0x1B);
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_fov(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = (eax >> 0x05) | (eax << 0x1B);
		    eax = eax ^ 0xCC78692Eu;
		    return eax;
		}

	}

	namespace Convar_Admin_Decryption
	{
		// decryptions::decrypt_bool
		std::uintptr_t decrypt_bool(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x3;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x1A8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace Convar_Server_Decryption
	{
		// decryptions::decrypt_bool
		std::uintptr_t decrypt_bool(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xCE60325Bu;
		        eax = (eax << 0x13) | (eax >> 0x0D);
		        eax = eax + 0xA48959Fu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_Action
		std::uintptr_t decrypt_Action(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax - 0x44519A01u;
		        eax = eax ^ 0xEF6D88Cu;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        eax = eax - 0x48BD351Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_int
		uint64_t encrypt_decrypt_int(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x1u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_int(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x1u;
		    return eax;
		}

		// decryptions::decrypt_int
		uint64_t encrypt_decrypt_int(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x1u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_int(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x1u;
		    return eax;
		}

		// decryptions::decrypt_int
		uint64_t encrypt_decrypt_int(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x1u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_int(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x1u;
		    return eax;
		}

		// decryptions::decrypt_int
		uint64_t encrypt_decrypt_int(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x1u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_int(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x1u;
		    return eax;
		}

		// decryptions::decrypt_int
		uint64_t encrypt_decrypt_int(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x1u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_int(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x1u;
		    return eax;
		}

	}

	namespace BaseProjectile_Decryption
	{
		// decryptions::decrypt_aimCone
		uint64_t encrypt_decrypt_aimCone(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x5E099DD0u;
		    eax = eax ^ 0xD4759399u;
		    eax = eax - 0x79AD09C2u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_aimCone(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax + 0x79AD09C2u;
		    eax = eax ^ 0xD4759399u;
		    eax = eax - 0x5E099DD0u;
		    return eax;
		}

		// decryptions::decrypt_recoil
		uint64_t encrypt_decrypt_recoil(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax ^ 0x899712E4u;
		    eax = eax - 0x3B4A71B2u;
		    eax = eax ^ 0x5742770Fu;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_recoil(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax ^ 0x5742770Fu;
		    eax = eax + 0x3B4A71B2u;
		    eax = eax ^ 0x899712E4u;
		    return eax;
		}

		// decryptions::decrypt_2
		std::uintptr_t decrypt_2(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xB2ED0CF9u;
		        eax = eax + 0x1350E729u;
		        eax = (eax << 0x12) | (eax >> 0x0E);
		        eax = eax + 0x132B2673u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace BaseCombatEntity_Decryption
	{
		// decryptions::decrypt_health
		std::uintptr_t decrypt_health(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xF04758DFu;
		        eax = (eax << 0x0C) | (eax >> 0x14);
		        eax = eax + 0xFCE0AA13u;
		        eax = (eax << 0x14) | (eax >> 0x0C);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace PlayerInput_Decryption
	{
		// decryptions::decrypt_state
		std::uintptr_t decrypt_state(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x93748B89u;
		        eax = eax + 0x96CB9157u;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_buttons
		std::uintptr_t decrypt_buttons(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax - 0x44519A01u;
		        eax = eax ^ 0xEF6D88Cu;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        eax = eax - 0x48BD351Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_aimAngles
		std::uintptr_t decrypt_aimAngles(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x15) | (eax << 0x0B);
		        eax = eax - 0x3BAD30FEu;
		        eax = eax ^ 0x7790C0A0u;
		        eax = eax + 0x6CE48E8Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace HeldEntity_Decryption
	{
		// decryptions::decrypt_viewModel
		std::uintptr_t decrypt_viewModel(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x2B99655Bu;
		        eax = eax + 0xC749C554u;
		        eax = (eax << 0x07) | (eax >> 0x19);
		        eax = eax + 0x784A90B1u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_nextAttackTime
		std::uintptr_t decrypt_nextAttackTime(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax - 0x44519A01u;
		        eax = eax ^ 0xEF6D88Cu;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        eax = eax - 0x48BD351Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_hostileScore
		std::uintptr_t decrypt_hostileScore(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x93748B89u;
		        eax = eax + 0x96CB9157u;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_3
		std::uintptr_t decrypt_3(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x87B56F4Fu;
		        eax = (eax << 0x19) | (eax >> 0x07);
		        eax = eax + 0x38B63AACu;
		        eax = eax ^ 0x2B99655Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_4
		std::uintptr_t decrypt_4(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xCE60325Bu;
		        eax = (eax << 0x13) | (eax >> 0x0D);
		        eax = eax + 0xA48959Fu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace BaseEntity_Decryption
	{
		// decryptions::decrypt_flags
		uint64_t encrypt_decrypt_flags(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax - 0x20u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_flags(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax + 0x20u;
		    return eax;
		}

		// decryptions::decrypt_parentEntity
		std::uintptr_t decrypt_parentEntity(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xC8390462u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        eax = eax - 0x4DC14BB8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace TOD_Sky_Decryption
	{
		// decryptions::decrypt_cycle
		uint64_t encrypt_decrypt_cycle(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax - r10d;
		    eax = eax + r10d;
		    eax = eax - r10d;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_cycle(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax + r10d;
		    eax = eax - r10d;
		    eax = eax + r10d;
		    return eax;
		}

		// decryptions::decrypt_day
		uint64_t encrypt_decrypt_day(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x1u;
		    eax = eax + 0x1u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_day(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x1u;
		    eax = eax - 0x1u;
		    return eax;
		}

	}

	namespace AutoTurret_Decryption
	{
		// decryptions::decrypt_target
		std::uintptr_t decrypt_target(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xC8390462u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        eax = eax - 0x4DC14BB8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_sightRange
		std::uintptr_t decrypt_sightRange(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x2B99655Bu;
		        eax = eax + 0xC749C554u;
		        eax = (eax << 0x07) | (eax >> 0x19);
		        eax = eax + 0x784A90B1u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_aimCone
		std::uintptr_t decrypt_aimCone(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x93748B89u;
		        eax = eax + 0x96CB9157u;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace PlayerWalkMovement_Decryption
	{
		// decryptions::decrypt_groundAngle
		std::uintptr_t decrypt_groundAngle(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x1E88CBFFu;
		        eax = (eax << 0x07) | (eax >> 0x19);
		        eax = eax ^ 0xBA6BB96Au;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_groundVelocity
		std::uintptr_t decrypt_groundVelocity(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax - 0x44519A01u;
		        eax = eax ^ 0xEF6D88Cu;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        eax = eax - 0x48BD351Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_maxVelocity
		std::uintptr_t decrypt_maxVelocity(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x19) | (eax << 0x07);
		        eax = eax ^ 0xDE9BD713u;
		        eax = (eax << 0x11) | (eax >> 0x0F);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace BuildingPrivlidge_Decryption
	{
		// decryptions::decrypt_upkeep
		std::uintptr_t decrypt_upkeep(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xC8390462u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        eax = eax - 0x4DC14BB8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_authorizedPlayers
		std::uintptr_t decrypt_authorizedPlayers(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x2B99655Bu;
		        eax = eax + 0xC749C554u;
		        eax = (eax << 0x07) | (eax >> 0x19);
		        eax = eax + 0x784A90B1u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_protectedMinutes
		std::uintptr_t decrypt_protectedMinutes(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x93748B89u;
		        eax = eax + 0x96CB9157u;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

}
