// Auto-generated by @decamped dm with any issues ill be happy to help
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <array>

namespace update
{
    namespace game_object
    {
        constexpr size_t m_Component = 0x30;
        constexpr size_t m_Name = 0x60;
    }
}

namespace Offsets
{
    constexpr auto dwBaseNetworkable                            = 0xe4910a0;
    constexpr auto ghandle                                     = 0xe7cbf30;
    constexpr auto entitycount                                 = 0x18;
    constexpr auto entityarray                                 = 0x10;

    namespace BN
    {
        constexpr auto StaticFields                            = 0xB8;    
        constexpr auto ClientEntities                          = 0x38;  
        constexpr auto EntityList                              = 0x10;   
        constexpr auto Buffer                                  = 0x18;    
        constexpr auto ArrayBase                               = 0x20;   
    }

    namespace Camera
    {
        constexpr auto Base                                    = 0xE485658;
        constexpr auto MainCamera_C                            = 0xE485658;
        constexpr auto StaticOffset                            = 0xB8;    // StaticFields
        constexpr auto ObjectOffset                            = 0x80;    // Instance
        constexpr auto Offset                                  = 0x10;    // Parent
        constexpr auto Matrix                                  = 0x30c;   // ViewMatrix
    }

    namespace BasePlayer
    {
        constexpr auto playerFlags                             = 0x630;
        constexpr auto playerTeam                              = 0x4b8;
        constexpr auto _displayName                            = 0x2c8;
        constexpr auto UserID                                  = 0x468;
        constexpr auto playerInput                             = 0x390;
        constexpr auto playerModel                             = 0x2f8;
        constexpr auto modelState                              = 0x0;
        constexpr auto PlayerEyes                              = 0x458;
        constexpr auto PlayerInventory                         = 0x698;
        constexpr auto baseMovement                            = 0x518;
        constexpr auto clActiveItem                            = 0x4e8;
        constexpr auto lifestate                               = 0x270;
        constexpr auto clothingBlocksAiming                    = 0x714;
        constexpr auto clothingMoveSpeedReduction              = 0x718;
    }

    namespace BaseCombatEntity
    {
        constexpr auto lifestate                               = 0x270;
        constexpr auto model                                   = 0xf0;
        constexpr auto _health                                 = 0x274;
        constexpr auto _maxHealth                              = 0x278;
    }

    namespace BaseEntity
    {
        constexpr auto model                                   = 0xf0;
        constexpr auto Bounds                                  = 0xc8;
        constexpr auto flags                                   = 0xf8;
    }

    namespace Model
    {
        constexpr auto boneTransforms                          = 0x50;
    }

    namespace PlayerModel
    {
        constexpr auto position                                = 0x1F8;
        constexpr auto velocity                                = 0x204;
        constexpr auto newVelocity                             = 0x21c;
        constexpr auto Rotation                                = 0x228;
        constexpr auto GestureConfig                           = 0x390;
        constexpr auto IsNpc__BackingField                     = 0x3dd;
        constexpr auto __Multimesh                             = 0x298;
    }

    namespace Item
    {
        constexpr auto ItemList                                = 0x60;
        constexpr auto ItemDefinition                          = 0xa0;
        constexpr auto item_definition                         = 0xa0;
        constexpr auto Amount                                  = 0x3c;
        constexpr auto CurrentHealth                           = 0x10;
        constexpr auto MaxHealth                               = 0x98;
        constexpr auto ammoCount                               = 0xd8;
        constexpr auto HeldEntity                              = 0x80;
        constexpr auto HeldEntity1                             = 0xa8;
        constexpr auto uid                                     = 0x18;
    }

    namespace ItemDefinition
    {
        constexpr auto ItemDisplayName                         = 0x40;
        constexpr auto ShortName                               = 0x28;
        constexpr auto shortname                               = 0x28;
        constexpr auto itemid                                  = 0x20;
        constexpr auto ItemMod                                 = 0x1a0;
    }

    namespace ItemContainer
    {
        constexpr auto itemList                                = 0x60;
    }

    namespace Magazine
    {
        constexpr auto definition                              = 0x10;
    }

    namespace PlayerInventory
    {
        constexpr auto ItemContainer                           = 0x58;
        constexpr auto containerBelt                           = 0x60;
        constexpr auto ContainerWear                           = 0x78;
    }

    namespace HeldEntity
    {
        constexpr auto ViewModel                               = 0x278;
        constexpr auto Magazine                                = 0x378;
    }

    namespace Entity
    {
        constexpr auto baseObject                              = 0x10;
        constexpr auto entityObject                            = 0x30;
        constexpr auto transform                               = 0x8;
        constexpr auto visualState                             = 0x38;
        constexpr auto position                                = 0x90;
    }

    namespace WorldItem
    {
        constexpr auto item                                    = 0x1e0;
    }

    namespace world
    {
        constexpr auto ItemClass                               = 0x1e0;
    }

    namespace AttackEntity
    {
        constexpr auto repeatDelay                             = 0x294;
        constexpr auto deployDelay                             = 0x290;
    }

    namespace BaseProjectile
    {
        constexpr auto reloadTime                              = 0x378;
        constexpr auto recoil                                  = 0x3a8;
        constexpr auto primaryMagazine                         = 0x380;
        constexpr auto aimconePenalty                          = 0x3c0;
        constexpr auto aimCone                                 = 0x3b0;
        constexpr auto aimconePenaltyPerShot                   = 0x3c0;
        constexpr auto aimSway                                 = 0x3a0;
        constexpr auto aimSwaySpeed                            = 0x3a4;
        constexpr auto stancePenaltyScale                      = 0x3d0;
        constexpr auto aimConePenaltyMax                       = 0x3c4;
        constexpr auto automatic                               = 0x338;
        constexpr auto hipAimCone                              = 0x3bc;
        constexpr auto isBurstWeapon                           = 0x3df;
        constexpr auto canChangeFireModes                      = 0x3e0;
        constexpr auto internalBurstFireRateScale              = 0x3e8;
        constexpr auto IsReloading                             = 0x424;
    }

    namespace Projectile
    {
        constexpr auto initialVelocity                         = 0x28;
        constexpr auto thickness                               = 0x3c;
        constexpr auto velocity                                = 0x15c;
        constexpr auto position                                = 0x168;
        constexpr auto sentPosition                            = 0x180;
        constexpr auto previousPosition                        = 0x18c;
        constexpr auto previousVelocity                        = 0x198;
        constexpr auto projectileID                            = 0x130;
        constexpr auto owner                                   = 0x128;
        constexpr auto hitTest                                 = 0x118;
    }

    namespace HitTest
    {
        constexpr auto HitTransform                            = 0x88;
        constexpr auto HitEntity                               = 0x70;
    }

    namespace RecoilProperties
    {
        constexpr auto recoilYawMin                            = 0x18;
        constexpr auto recoilYawMax                            = 0x1c;
        constexpr auto recoilPitchMin                          = 0x20;
        constexpr auto recoilPitchMax                          = 0x24;
        constexpr auto aimconeCurveScale                       = 0x60;
        constexpr auto newRecoilOverride                       = 0x80;
    }

    namespace BaseViewModel
    {
        constexpr auto BaseViewModel_C                         = 0xe444338;
        constexpr auto ListPTR                                 = 0x188;
        constexpr auto IronSights                              = 0xe8;
        constexpr auto AnimationEvents                         = 0x100;
        constexpr auto ViewmodelBob                            = 0x80;
        constexpr auto ViewmodelLower                          = 0xc8;
        constexpr auto ViewmodelSway                           = 0xb0;
    }

    namespace ItemModWearable
    {
        constexpr auto blocksAiming                            = 0x5c;
        constexpr auto occlusionType                           = 0x58;
    }

    namespace Translate_Phrase
    {
        constexpr auto English                                 = 0x20;
    }

    namespace SkinnedMultiMeshRenderers
    {
        constexpr auto Renderers__BackingField                 = 0x50;
    }

    namespace ModelState
    {
        constexpr auto Flags                                   = 0x0;
        constexpr auto WaterLevel                              = 0x0;
    }

    namespace HackableLockedCrate
    {
        constexpr auto TimerText                               = 0x3d8;
    }

    namespace BuildingPrivlidge
    {
        constexpr auto UpkeepTime                              = 0x3cc;
    }

    namespace PatrolHelicopter
    {
        constexpr auto weakspots                               = 0x420;
    }

    namespace CompoundBowWeapon
    {
        constexpr auto stringHoldDurationMax                   = 0x478;
        constexpr auto movementPenaltyRampUpTime               = 0x488;
    }

    namespace FlintStrikeWeapon
    {
        constexpr auto successFraction                         = 0x460;
        constexpr auto _didSparkThisFrame                      = 0x470;
    }

    namespace BowWeapon
    {
        constexpr auto attackReady                             = 0x460;
        constexpr auto nopullback                              = 0x464;
    }

    namespace ActiveItem
    {
        constexpr auto clActiveItem                            = 0x4e8;
    }

    namespace BaseNetworkable
    {
        constexpr auto BaseNetworkable_C                       = 0xe4910a0;
        constexpr auto static_fields                           = 0xb8;
        constexpr auto wrapper_class_ptr                       = 0x38;
        constexpr auto parent_static_fields                    = 0x10;
        constexpr auto entity                                  = 0x10;
    }

    namespace ListComponent_Projectile
    {
        constexpr auto ListComponent_Projectile_C              = 0xe4c31a8;
        constexpr auto static_fields                           = 0xb8;
        constexpr auto instance                                = 0x18;
        constexpr auto instance_two                            = 0x10;
    }

    namespace TodSky
    {
        constexpr auto TodSky_C                                = 0xe436d28;
        constexpr auto Instance                                = 0x88;
    }

    namespace Convar_Admin
    {
        constexpr auto TypeInfo                                = 0xe4e1db8;
    }

    namespace Convar_Graphics
    {
        constexpr auto TypeInfo                                = 0xe43c980;
    }

    namespace Convar_Server
    {
        constexpr auto TypeInfo                                = 0xe490ce0;
    }

    namespace SingletonClimate
    {
        constexpr auto Climate_C                               = 0xe43cb70;
        constexpr auto static_fields                           = 0xb8;
        constexpr auto Instance                                = 0x30;
    }

    namespace GameManager
    {
        constexpr auto GameManager_C                           = 0xe491328;
        constexpr auto Static_fields                           = 0xb8;
        constexpr auto Instance                                = 0x18;
        constexpr auto Pool                                    = 0x20;
        constexpr auto Stack                                   = 0x18;
    }

    namespace ItemIcon
    {
        constexpr auto ItemIcon_C                              = 0xe4b24b0;
        constexpr auto Static_fields                           = 0xc0;
        constexpr auto Instance                                = 0x18;
    }

    namespace Il2Cpp
    {
        constexpr auto sTypeInfoDefinitionTable                = 0xe7d0168;
        constexpr auto GetHandle                               = 0xe7cbf30;
    }

    namespace SceneManager
    {
        constexpr auto GetActiveScene                          = 0xbeff3e0;
    }

} // namespace Offsets
